mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: bes-exam-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.31.175.230:3306/db_exam_center?serverTimezone=Asia/Shanghai&useSSL=false
    username: dms
    password: BOSSteam05@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
